# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 16:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20, null=True)),
                ('lastName', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[(b'India', b'India'), (b'USA', b'USA'), (b'China', b'China')], default=b'India', max_length=50)),
                ('emailID', models.CharField(max_length=50, validators=[django.core.validators.EmailValidator])),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
