# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
