# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 17:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161107_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailID',
            field=models.CharField(max_length=50, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
