# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 09:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161107_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailID',
            field=models.EmailField(default=b'example@example.com', max_length=50, validators=[django.core.validators.EmailValidator]),
        ),
    ]
